from django.core.management.base import BaseCommand
from advisory.models import DiseaseAdvisory

ADVISORY_DATA = [
    {
        'disease_key': 'Apple___Apple_scab',
        'disease_name': 'Apple Scab',
        'plant': 'Apple',
        'disease': 'Apple Scab',
        'is_healthy': False,
        'symptoms': 'Olive-green or brown spots on leaves and fruit. Leaves may curl and drop early. Dark scabby lesions appear on fruit surface.',
        'causes': 'Caused by fungus Venturia inaequalis. Spreads through water splash and wind during wet spring weather.',
        'organic_treatment': 'Apply neem oil spray every 7-10 days. Use sulfur-based fungicide. Remove and destroy infected leaves immediately.',
        'chemical_treatment': 'Apply Captan, Mancozeb or Myclobutanil fungicide. Spray at 7-day intervals during wet weather.',
        'prevention': 'Plant resistant apple varieties. Ensure good air circulation. Rake and destroy fallen leaves. Avoid overhead irrigation.',
        'severity_level': 'Medium',
        'urgency_message': 'Treat within 7 days to prevent fruit loss.'
    },
    {
        'disease_key': 'Apple___Black_rot',
        'disease_name': 'Apple Black Rot',
        'plant': 'Apple',
        'disease': 'Black Rot',
        'is_healthy': False,
        'symptoms': 'Brown circular lesions on leaves with purple borders. Fruit shows brown rotting starting from the core. Cankers appear on branches.',
        'causes': 'Caused by fungus Botryosphaeria obtusa. Enters through wounds and insect damage. Spreads in warm humid conditions.',
        'organic_treatment': 'Prune infected branches 15cm below visible infection. Apply copper-based spray. Remove mummified fruits from tree.',
        'chemical_treatment': 'Apply Captan or Thiophanate-methyl fungicide. Treat cankers with wound sealant after pruning.',
        'prevention': 'Remove dead wood regularly. Control insect pests that cause wounds. Maintain tree vigor with proper nutrition.',
        'severity_level': 'Severe',
        'urgency_message': 'Act immediately - can destroy entire fruit crop.'
    },
    {
        'disease_key': 'Apple___Cedar_apple_rust',
        'disease_name': 'Cedar Apple Rust',
        'plant': 'Apple',
        'disease': 'Cedar Apple Rust',
        'is_healthy': False,
        'symptoms': 'Bright orange-yellow spots on upper leaf surface. Tube-like structures on leaf undersides. Premature defoliation in severe cases.',
        'causes': 'Caused by fungus Gymnosporangium juniperi-virginianae. Requires both apple and cedar/juniper trees to complete lifecycle.',
        'organic_treatment': 'Apply sulfur or copper fungicide at bud break. Remove nearby cedar/juniper trees if possible.',
        'chemical_treatment': 'Apply Myclobutanil or Propiconazole fungicide from pink bud stage through petal fall.',
        'prevention': 'Plant rust-resistant apple varieties. Remove juniper/cedar trees within 1km radius. Apply protective sprays in spring.',
        'severity_level': 'Medium',
        'urgency_message': 'Begin treatment at first sign of orange spots.'
    },
    {
        'disease_key': 'Apple___healthy',
        'disease_name': 'Healthy Apple',
        'plant': 'Apple',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No symptoms detected. Leaves appear green and healthy.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Continue regular organic care. Apply compost and mulch.',
        'chemical_treatment': 'No treatment needed. Continue preventive care.',
        'prevention': 'Maintain regular pruning. Ensure proper nutrition and irrigation. Monitor regularly for early signs of disease.',
        'severity_level': 'Healthy',
        'urgency_message': 'Your plant is healthy! Maintain good care practices.'
    },
    {
        'disease_key': 'Blueberry___healthy',
        'disease_name': 'Healthy Blueberry',
        'plant': 'Blueberry',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No symptoms. Plant looks vigorous and healthy.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply acidic fertilizer. Mulch with pine needles.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Maintain soil pH 4.5-5.5. Ensure good drainage. Prune annually for air circulation.',
        'severity_level': 'Healthy',
        'urgency_message': 'Your blueberry plant is healthy!'
    },
    {
        'disease_key': 'Cherry_(including_sour)___Powdery_mildew',
        'disease_name': 'Cherry Powdery Mildew',
        'plant': 'Cherry',
        'disease': 'Powdery Mildew',
        'is_healthy': False,
        'symptoms': 'White powdery coating on young leaves and shoots. Leaves curl and distort. Stunted growth in severe infections.',
        'causes': 'Caused by fungus Podosphaera clandestina. Thrives in warm dry days with cool nights. Spread by wind.',
        'organic_treatment': 'Spray baking soda solution (1 tsp per litre water). Apply neem oil. Use potassium bicarbonate spray.',
        'chemical_treatment': 'Apply Myclobutanil, Trifloxystrobin or Sulfur fungicide. Spray every 10-14 days.',
        'prevention': 'Avoid overhead watering. Ensure good air circulation. Remove infected shoots promptly.',
        'severity_level': 'Medium',
        'urgency_message': 'Treat promptly to protect new growth.'
    },
    {
        'disease_key': 'Cherry_(including_sour)___healthy',
        'disease_name': 'Healthy Cherry',
        'plant': 'Cherry',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Leaves are green and normal.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply balanced organic fertilizer in spring.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Prune for open canopy. Monitor for pests. Water at base not overhead.',
        'severity_level': 'Healthy',
        'urgency_message': 'Cherry plant is healthy!'
    },
    {
        'disease_key': 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
        'disease_name': 'Corn Gray Leaf Spot',
        'plant': 'Corn',
        'disease': 'Gray Leaf Spot',
        'is_healthy': False,
        'symptoms': 'Long rectangular gray-tan lesions between leaf veins. Lesions run parallel to leaf margins. Severe infection causes blighting.',
        'causes': 'Caused by fungus Cercospora zeae-maydis. Favored by warm humid weather with heavy dew. Survives in crop residue.',
        'organic_treatment': 'Rotate crops every 2-3 years. Till infected residue into soil. Apply compost to improve plant immunity.',
        'chemical_treatment': 'Apply Azoxystrobin, Pyraclostrobin or Propiconazole fungicide at tasseling stage.',
        'prevention': 'Plant resistant hybrids. Rotate with non-host crops. Manage crop residue. Ensure adequate plant spacing.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply fungicide before tasseling for best results.'
    },
    {
        'disease_key': 'Corn_(maize)___Common_rust_',
        'disease_name': 'Corn Common Rust',
        'plant': 'Corn',
        'disease': 'Common Rust',
        'is_healthy': False,
        'symptoms': 'Small cinnamon-brown pustules on both leaf surfaces. Pustules rupture releasing rusty brown spores. Severe infection causes yellowing.',
        'causes': 'Caused by fungus Puccinia sorghi. Spores spread by wind from tropical regions. Favored by cool wet conditions.',
        'organic_treatment': 'Apply neem oil spray. Remove severely infected plants. Improve air circulation through spacing.',
        'chemical_treatment': 'Apply Mancozeb, Azoxystrobin or Trifloxystrobin fungicide. Early application is most effective.',
        'prevention': 'Plant rust-resistant corn varieties. Early planting avoids peak spore periods. Monitor regularly.',
        'severity_level': 'Medium',
        'urgency_message': 'Monitor spread rate and apply fungicide if severe.'
    },
    {
        'disease_key': 'Corn_(maize)___Northern_Leaf_Blight',
        'disease_name': 'Corn Northern Leaf Blight',
        'plant': 'Corn',
        'disease': 'Northern Leaf Blight',
        'is_healthy': False,
        'symptoms': 'Long cigar-shaped gray-green lesions on leaves. Lesions turn tan with wavy edges. Severe infection before silking causes major yield loss.',
        'causes': 'Caused by fungus Exserohilum turcicum. Survives in infected residue. Spreads by wind and rain splash in cool humid weather.',
        'organic_treatment': 'Crop rotation with non-corn crops. Deep tillage of infected residue. Apply compost for plant health.',
        'chemical_treatment': 'Apply Propiconazole or Azoxystrobin fungicide at first sign. Repeat every 14 days if wet.',
        'prevention': 'Plant resistant hybrids. Rotate crops. Manage residue. Avoid late planting.',
        'severity_level': 'Severe',
        'urgency_message': 'Apply fungicide immediately to protect yield.'
    },
    {
        'disease_key': 'Corn_(maize)___healthy',
        'disease_name': 'Healthy Corn',
        'plant': 'Corn',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No symptoms. Green healthy leaves with good growth.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply nitrogen-rich compost. Ensure adequate irrigation.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Maintain proper plant spacing. Rotate crops. Monitor for pests.',
        'severity_level': 'Healthy',
        'urgency_message': 'Corn crop is healthy!'
    },
    {
        'disease_key': 'Grape___Black_rot',
        'disease_name': 'Grape Black Rot',
        'plant': 'Grape',
        'disease': 'Black Rot',
        'is_healthy': False,
        'symptoms': 'Small brown circular spots on leaves with black borders. Fruit shrivels into hard black mummies. Tan lesions on shoots and stems.',
        'causes': 'Caused by fungus Guignardia bidwellii. Spreads during warm wet weather. Overwinters in mummified fruit and infected canes.',
        'organic_treatment': 'Remove all mummified fruit immediately. Prune infected canes. Apply copper-based spray at bud break.',
        'chemical_treatment': 'Apply Myclobutanil or Mancozeb from bud break through fruit development. Spray every 10-14 days.',
        'prevention': 'Remove mummified fruit from vineyard. Prune for air circulation. Train vines for sun exposure.',
        'severity_level': 'Severe',
        'urgency_message': 'Remove infected fruit immediately to prevent spread.'
    },
    {
        'disease_key': 'Grape___Esca_(Black_Measles)',
        'disease_name': 'Grape Esca (Black Measles)',
        'plant': 'Grape',
        'disease': 'Esca Black Measles',
        'is_healthy': False,
        'symptoms': 'Tiger-stripe pattern on leaves with yellow and brown bands. Berries show dark spots (measles). Sudden wilting of entire shoots in summer.',
        'causes': 'Complex of wood-rotting fungi including Phaeomoniella chlamydospora. Enters through pruning wounds. Long-term trunk disease.',
        'organic_treatment': 'Paint pruning wounds with wound sealant immediately. Remove and burn severely infected wood.',
        'chemical_treatment': 'No fully effective chemical treatment. Apply Thiophanate-methyl as protective measure on wounds.',
        'prevention': 'Prune during dry weather. Seal all pruning cuts immediately. Avoid large pruning wounds.',
        'severity_level': 'Severe',
        'urgency_message': 'Long-term disease - consult viticulture expert immediately.'
    },
    {
        'disease_key': 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
        'disease_name': 'Grape Leaf Blight',
        'plant': 'Grape',
        'disease': 'Leaf Blight',
        'is_healthy': False,
        'symptoms': 'Dark brown irregular spots on older leaves. Spots have yellow halo. Severe infection causes defoliation and weakens vine.',
        'causes': 'Caused by fungus Isariopsis clavispora. Favored by warm humid conditions. Affects older leaves first.',
        'organic_treatment': 'Apply copper hydroxide spray. Remove infected leaves. Improve air circulation through pruning.',
        'chemical_treatment': 'Apply Mancozeb or Captan fungicide. Spray after rain events.',
        'prevention': 'Maintain good canopy management. Avoid waterlogging. Apply preventive copper sprays.',
        'severity_level': 'Medium',
        'urgency_message': 'Treat within 5 days to prevent defoliation.'
    },
    {
        'disease_key': 'Grape___healthy',
        'disease_name': 'Healthy Grape',
        'plant': 'Grape',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Vine is growing vigorously.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply balanced organic fertilizer. Mulch around base.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Maintain proper canopy management. Monitor weekly during growing season.',
        'severity_level': 'Healthy',
        'urgency_message': 'Grape vine is healthy!'
    },
    {
        'disease_key': 'Orange___Haunglongbing_(Citrus_greening)',
        'disease_name': 'Citrus Greening (HLB)',
        'plant': 'Orange',
        'disease': 'Citrus Greening HLB',
        'is_healthy': False,
        'symptoms': 'Yellow mottled leaves with asymmetric blotching. Small lopsided fruit with bitter taste. Twig dieback and premature fruit drop.',
        'causes': 'Caused by bacteria Candidatus Liberibacter asiaticus. Spread by Asian citrus psyllid insect. No cure currently available.',
        'organic_treatment': 'Remove and destroy infected trees immediately. Control psyllid with insecticidal soap spray.',
        'chemical_treatment': 'Control psyllid vector with Imidacloprid or Thiamethoxam. No cure for HLB itself.',
        'prevention': 'Use certified disease-free nursery stock. Control psyllid populations aggressively. Remove infected trees.',
        'severity_level': 'Severe',
        'urgency_message': 'CRITICAL: No cure exists. Remove infected trees immediately.'
    },
    {
        'disease_key': 'Peach___Bacterial_spot',
        'disease_name': 'Peach Bacterial Spot',
        'plant': 'Peach',
        'disease': 'Bacterial Spot',
        'is_healthy': False,
        'symptoms': 'Water-soaked spots on leaves that turn brown with yellow halos. Fruit shows small circular spots that crack open. Defoliation in severe cases.',
        'causes': 'Caused by bacteria Xanthomonas arboricola. Spreads through rain splash and wind. Enters through stomata and wounds.',
        'organic_treatment': 'Apply copper-based bactericide spray. Prune to improve air circulation. Avoid overhead irrigation.',
        'chemical_treatment': 'Apply fixed copper or oxytetracycline sprays from bud swell through summer. Repeat every 7-10 days in wet weather.',
        'prevention': 'Plant resistant varieties. Avoid sites with frequent spring rains. Maintain tree vigor with proper nutrition.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply copper spray before rain events.'
    },
    {
        'disease_key': 'Peach___healthy',
        'disease_name': 'Healthy Peach',
        'plant': 'Peach',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms detected.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply balanced fertilizer in early spring.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Prune annually for open center. Monitor for insects. Thin fruit for better size.',
        'severity_level': 'Healthy',
        'urgency_message': 'Peach tree is healthy!'
    },
    {
        'disease_key': 'Pepper,_bell___Bacterial_spot',
        'disease_name': 'Pepper Bacterial Spot',
        'plant': 'Pepper',
        'disease': 'Bacterial Spot',
        'is_healthy': False,
        'symptoms': 'Small water-soaked spots on leaves that enlarge and turn brown. Raised scabby spots on fruit. Severe defoliation causes sunscald on fruit.',
        'causes': 'Caused by Xanthomonas euvesicatoria bacteria. Spreads by rain splash and contaminated tools. Favored by warm wet weather.',
        'organic_treatment': 'Apply copper hydroxide spray. Remove infected leaves. Avoid working in plants when wet.',
        'chemical_treatment': 'Apply copper-based bactericide plus Mancozeb every 7 days. Begin at first symptom.',
        'prevention': 'Use disease-free certified seed. Rotate crops. Avoid overhead irrigation. Disinfect tools regularly.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply copper spray and remove infected leaves today.'
    },
    {
        'disease_key': 'Pepper,_bell___healthy',
        'disease_name': 'Healthy Bell Pepper',
        'plant': 'Pepper',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Healthy green leaves and good growth.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply compost tea. Ensure consistent moisture.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Mulch to retain moisture. Support plants with stakes. Monitor for aphids.',
        'severity_level': 'Healthy',
        'urgency_message': 'Pepper plant is healthy!'
    },
    {
        'disease_key': 'Potato___Early_blight',
        'disease_name': 'Potato Early Blight',
        'plant': 'Potato',
        'disease': 'Early Blight',
        'is_healthy': False,
        'symptoms': 'Dark brown circular lesions with concentric rings (target pattern) on older lower leaves. Yellow halo around lesions. Premature leaf drop.',
        'causes': 'Caused by fungus Alternaria solani. Favored by warm days and cool nights with heavy dew. Survives in infected plant debris.',
        'organic_treatment': 'Remove and destroy infected lower leaves. Apply neem oil or copper spray. Ensure adequate plant nutrition.',
        'chemical_treatment': 'Apply Chlorothalonil, Mancozeb or Azoxystrobin fungicide every 7-10 days from first symptom.',
        'prevention': 'Plant certified disease-free seed potatoes. Rotate crops every 3-4 years. Avoid overhead irrigation.',
        'severity_level': 'Medium',
        'urgency_message': 'Remove lower infected leaves immediately.'
    },
    {
        'disease_key': 'Potato___Late_blight',
        'disease_name': 'Potato Late Blight',
        'plant': 'Potato',
        'disease': 'Late Blight',
        'is_healthy': False,
        'symptoms': 'Water-soaked gray-green spots on leaves that turn brown-black rapidly. White fungal growth on leaf undersides. Tubers show brown rot inside.',
        'causes': 'Caused by oomycete Phytophthora infestans. Spreads rapidly in cool wet conditions. Caused the Irish Potato Famine.',
        'organic_treatment': 'Remove infected plants immediately. Apply copper-based spray. Avoid wetting foliage.',
        'chemical_treatment': 'Apply Metalaxyl, Dimethomorph or Cymoxanil+Mancozeb fungicide. Act within 24 hours of detection.',
        'prevention': 'Plant resistant varieties. Use certified seed. Destroy infected volunteers. Avoid overhead irrigation.',
        'severity_level': 'Severe',
        'urgency_message': 'URGENT: Act within 24 hours - spreads extremely fast.'
    },
    {
        'disease_key': 'Potato___healthy',
        'disease_name': 'Healthy Potato',
        'plant': 'Potato',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Green healthy foliage.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Hill soil around stems. Apply potassium-rich fertilizer.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Monitor weekly for blight symptoms especially in wet weather.',
        'severity_level': 'Healthy',
        'urgency_message': 'Potato crop is healthy!'
    },
    {
        'disease_key': 'Raspberry___healthy',
        'disease_name': 'Healthy Raspberry',
        'plant': 'Raspberry',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No symptoms. Canes are healthy with good leaf color.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply mulch around base. Feed with balanced fertilizer after fruiting.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Remove old fruited canes after harvest. Ensure good air circulation.',
        'severity_level': 'Healthy',
        'urgency_message': 'Raspberry plant is healthy!'
    },
    {
        'disease_key': 'Soybean___healthy',
        'disease_name': 'Healthy Soybean',
        'plant': 'Soybean',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Plants growing vigorously.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply rhizobium inoculant. Ensure good drainage.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Rotate with non-legume crops. Monitor for soybean aphid and rust.',
        'severity_level': 'Healthy',
        'urgency_message': 'Soybean crop is healthy!'
    },
    {
        'disease_key': 'Squash___Powdery_mildew',
        'disease_name': 'Squash Powdery Mildew',
        'plant': 'Squash',
        'disease': 'Powdery Mildew',
        'is_healthy': False,
        'symptoms': 'White powdery spots on upper leaf surface. Spots enlarge to cover entire leaf. Leaves yellow and die. Reduced fruit quality.',
        'causes': 'Caused by fungi Podosphaera xanthii or Erysiphe cichoracearum. Favored by warm dry weather. Spreads by wind.',
        'organic_treatment': 'Spray diluted neem oil every 7 days. Apply potassium bicarbonate solution. Remove severely infected leaves.',
        'chemical_treatment': 'Apply Myclobutanil, Trifloxystrobin or Sulfur fungicide. Begin at first sign of white powder.',
        'prevention': 'Plant resistant varieties. Avoid overcrowding. Water at base in morning.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply neem oil or fungicide within 3 days.'
    },
    {
        'disease_key': 'Strawberry___Leaf_scorch',
        'disease_name': 'Strawberry Leaf Scorch',
        'plant': 'Strawberry',
        'disease': 'Leaf Scorch',
        'is_healthy': False,
        'symptoms': 'Small dark purple spots on leaf surface that enlarge with reddish-purple borders. Leaf surface appears scorched. Severe infection causes defoliation.',
        'causes': 'Caused by fungus Diplocarpon earlianum. Spreads by water splash. Favored by warm wet weather.',
        'organic_treatment': 'Remove infected leaves. Apply copper-based spray. Improve drainage and air circulation.',
        'chemical_treatment': 'Apply Captan or Myclobutanil fungicide. Spray every 10-14 days during wet weather.',
        'prevention': 'Plant in well-drained soil. Avoid overhead irrigation. Remove old leaves after harvest.',
        'severity_level': 'Medium',
        'urgency_message': 'Remove infected leaves and apply copper spray.'
    },
    {
        'disease_key': 'Strawberry___healthy',
        'disease_name': 'Healthy Strawberry',
        'plant': 'Strawberry',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Healthy green leaves.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply balanced strawberry fertilizer. Mulch with straw.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Renew beds every 3 years. Remove runners that crowd plants.',
        'severity_level': 'Healthy',
        'urgency_message': 'Strawberry plant is healthy!'
    },
    {
        'disease_key': 'Tomato___Bacterial_spot',
        'disease_name': 'Tomato Bacterial Spot',
        'plant': 'Tomato',
        'disease': 'Bacterial Spot',
        'is_healthy': False,
        'symptoms': 'Small water-soaked spots on leaves that turn dark brown with yellow halo. Raised scabby spots on fruit. Defoliation in severe cases.',
        'causes': 'Caused by Xanthomonas vesicatoria bacteria. Spreads by rain, irrigation and handling. Favored by warm wet weather.',
        'organic_treatment': 'Apply copper hydroxide spray every 7 days. Avoid overhead watering. Remove infected leaves.',
        'chemical_treatment': 'Apply copper bactericide plus Mancozeb fungicide. Spray every 5-7 days in wet weather.',
        'prevention': 'Use certified disease-free seeds. Rotate crops 2-3 years. Stake plants for air circulation.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply copper spray and remove infected leaves today.'
    },
    {
        'disease_key': 'Tomato___Early_blight',
        'disease_name': 'Tomato Early Blight',
        'plant': 'Tomato',
        'disease': 'Early Blight',
        'is_healthy': False,
        'symptoms': 'Dark brown target-like concentric ring lesions on lower leaves. Yellow halo around lesions. Stem lesions cause collar rot in seedlings.',
        'causes': 'Caused by Alternaria solani fungus. Survives in soil and plant debris. Spreads through wind and water splash.',
        'organic_treatment': 'Remove lower infected leaves. Apply neem oil spray weekly. Mulch to prevent soil splash.',
        'chemical_treatment': 'Apply Chlorothalonil or Mancozeb every 7 days. Begin treatment early in season.',
        'prevention': 'Stake plants to keep off ground. Mulch heavily. Rotate crops. Water at base.',
        'severity_level': 'Medium',
        'urgency_message': 'Remove infected lower leaves immediately.'
    },
    {
        'disease_key': 'Tomato___Late_blight',
        'disease_name': 'Tomato Late Blight',
        'plant': 'Tomato',
        'disease': 'Late Blight',
        'is_healthy': False,
        'symptoms': 'Large irregular dark green to brown water-soaked lesions on leaves. White fuzzy growth on leaf underside in humid conditions. Brown greasy lesions on fruit.',
        'causes': 'Caused by Phytophthora infestans. Spreads rapidly in cool wet conditions. Wind-borne spores can travel miles.',
        'organic_treatment': 'Remove and bag infected plants immediately. Apply copper-based spray preventively.',
        'chemical_treatment': 'Apply Metalaxyl+Mancozeb or Cymoxanil immediately. Repeat every 5-7 days.',
        'prevention': 'Use resistant varieties. Avoid overhead irrigation. Destroy infected plant debris completely.',
        'severity_level': 'Severe',
        'urgency_message': 'URGENT: Remove infected plants immediately before it spreads.'
    },
    {
        'disease_key': 'Tomato___Leaf_Mold',
        'disease_name': 'Tomato Leaf Mold',
        'plant': 'Tomato',
        'disease': 'Leaf Mold',
        'is_healthy': False,
        'symptoms': 'Pale greenish-yellow spots on upper leaf surface. Olive-green to gray velvety mold on leaf undersides. Lower leaves affected first.',
        'causes': 'Caused by fungus Passalora fulva. Thrives in high humidity above 85%. Common in greenhouses and polytunnels.',
        'organic_treatment': 'Improve ventilation immediately. Reduce humidity. Apply copper-based spray. Remove infected leaves.',
        'chemical_treatment': 'Apply Chlorothalonil or Mancozeb fungicide. Improve air circulation first.',
        'prevention': 'Maintain humidity below 85%. Ensure good greenhouse ventilation. Plant with adequate spacing.',
        'severity_level': 'Medium',
        'urgency_message': 'Improve ventilation immediately to reduce humidity.'
    },
    {
        'disease_key': 'Tomato___Septoria_leaf_spot',
        'disease_name': 'Tomato Septoria Leaf Spot',
        'plant': 'Tomato',
        'disease': 'Septoria Leaf Spot',
        'is_healthy': False,
        'symptoms': 'Many small circular spots with dark borders and light gray centers on lower leaves. Tiny black dots visible in center of spots. Rapid defoliation.',
        'causes': 'Caused by fungus Septoria lycopersici. Spreads by water splash. Survives in infected debris and weeds.',
        'organic_treatment': 'Remove infected lower leaves immediately. Apply copper spray. Mulch to prevent soil splash.',
        'chemical_treatment': 'Apply Chlorothalonil, Mancozeb or Azoxystrobin every 7-10 days.',
        'prevention': 'Avoid overhead irrigation. Stake plants. Rotate crops. Remove plant debris at end of season.',
        'severity_level': 'Medium',
        'urgency_message': 'Remove lower leaves and apply fungicide within 48 hours.'
    },
    {
        'disease_key': 'Tomato___Spider_mites Two-spotted_spider_mite',
        'disease_name': 'Tomato Spider Mites',
        'plant': 'Tomato',
        'disease': 'Spider Mites',
        'is_healthy': False,
        'symptoms': 'Fine stippling or bronzing on upper leaf surface. Tiny webbing on leaf undersides. Leaves turn yellow then brown and drop.',
        'causes': 'Caused by Tetranychus urticae (two-spotted spider mite). Thrives in hot dry conditions. Reproduces rapidly.',
        'organic_treatment': 'Spray plants with strong water jet. Apply neem oil or insecticidal soap every 5-7 days. Introduce predatory mites.',
        'chemical_treatment': 'Apply Abamectin or Spiromesifen miticide. Rotate miticides to prevent resistance.',
        'prevention': 'Maintain adequate irrigation. Avoid water stress. Avoid broad-spectrum pesticides that kill natural predators.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply neem oil spray immediately - mites multiply fast.'
    },
    {
        'disease_key': 'Tomato___Target_Spot',
        'disease_name': 'Tomato Target Spot',
        'plant': 'Tomato',
        'disease': 'Target Spot',
        'is_healthy': False,
        'symptoms': 'Brown circular lesions with concentric rings on leaves. Lesions have yellow halo. Dark brown lesions on fruit with sunken centers.',
        'causes': 'Caused by fungus Corynespora cassiicola. Favored by warm wet conditions with high humidity.',
        'organic_treatment': 'Remove infected leaves. Improve air circulation. Apply copper-based spray preventively.',
        'chemical_treatment': 'Apply Azoxystrobin or Chlorothalonil fungicide every 7-14 days.',
        'prevention': 'Stake and prune tomatoes for air circulation. Avoid overhead irrigation. Rotate crops.',
        'severity_level': 'Medium',
        'urgency_message': 'Apply fungicide and improve air circulation.'
    },
    {
        'disease_key': 'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
        'disease_name': 'Tomato Yellow Leaf Curl Virus',
        'plant': 'Tomato',
        'disease': 'Yellow Leaf Curl Virus',
        'is_healthy': False,
        'symptoms': 'Upward curling and yellowing of young leaves. Stunted plant growth. Flowers drop without setting fruit. Plants look bushy.',
        'causes': 'Caused by Tomato yellow leaf curl virus (TYLCV). Transmitted by whitefly Bemisia tabaci. No cure once infected.',
        'organic_treatment': 'Remove and destroy infected plants immediately. Use yellow sticky traps to monitor whiteflies. Apply neem oil to control whiteflies.',
        'chemical_treatment': 'Control whitefly vector with Imidacloprid or Thiamethoxam. No treatment for the virus itself.',
        'prevention': 'Use virus-resistant tomato varieties. Install insect-proof nets. Control whitefly populations aggressively.',
        'severity_level': 'Severe',
        'urgency_message': 'URGENT: Remove infected plants immediately. Control whiteflies.'
    },
    {
        'disease_key': 'Tomato___Tomato_mosaic_virus',
        'disease_name': 'Tomato Mosaic Virus',
        'plant': 'Tomato',
        'disease': 'Mosaic Virus',
        'is_healthy': False,
        'symptoms': 'Mosaic pattern of light and dark green on leaves. Leaves may be distorted or fern-like. Stunted growth. Reduced fruit quality.',
        'causes': 'Caused by Tomato mosaic virus (ToMV). Spreads through infected tools, hands and seeds. Extremely stable in soil.',
        'organic_treatment': 'Remove infected plants. Wash hands with soap before handling plants. Disinfect all tools with bleach solution.',
        'chemical_treatment': 'No chemical cure. Focus on prevention and removal of infected plants.',
        'prevention': 'Use virus-free certified seeds. Disinfect tools. Wash hands before working. Remove weeds that harbor virus.',
        'severity_level': 'Severe',
        'urgency_message': 'Remove infected plants and disinfect all tools immediately.'
    },
    {
        'disease_key': 'Tomato___healthy',
        'disease_name': 'Healthy Tomato',
        'plant': 'Tomato',
        'disease': 'Healthy',
        'is_healthy': True,
        'symptoms': 'No disease symptoms. Green healthy leaves and good growth.',
        'causes': 'No disease detected.',
        'organic_treatment': 'Apply balanced tomato fertilizer. Mulch around base.',
        'chemical_treatment': 'No treatment needed.',
        'prevention': 'Stake plants. Water consistently at base. Monitor weekly for early disease signs.',
        'severity_level': 'Healthy',
        'urgency_message': 'Tomato plant is perfectly healthy!'
    },
]


class Command(BaseCommand):
    help = 'Seed advisory data for all 38 plant disease classes'

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for data in ADVISORY_DATA:
            obj, is_created = DiseaseAdvisory.objects.update_or_create(
                disease_key=data['disease_key'],
                defaults=data
            )
            if is_created:
                created += 1
            else:
                updated += 1
        self.stdout.write(
            self.style.SUCCESS(
                f'Advisory seeded: {created} created, {updated} updated'
            )
        )
