# Generated by Django 5.2.14 on 2026-05-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_host', models.CharField(max_length=100)),
                ('disease_name', models.CharField(max_length=200)),
                ('causative_agent', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Severe', 'Severe')], max_length=10)),
                ('pathogen', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('primary_symptoms', models.TextField()),
                ('preventative_culturing', models.TextField()),
                ('organic_treatment', models.TextField()),
                ('chemical_controls', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disease Advisory',
                'verbose_name_plural': 'Disease Advisories',
                'ordering': ['crop_host', 'disease_name'],
            },
        ),
    ]
