# Generated by Django 5.2.14 on 2026-05-19 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('disease_name', models.CharField(max_length=200)),
                ('plant', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('is_healthy', models.BooleanField(default=False)),
                ('top3_json', models.TextField(blank=True, default='[]')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
