# Generated by Django 5.2.14 on 2026-05-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasedetection',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='image_hash',
            field=models.CharField(blank=True, help_text='MD5 hash for duplicate detection', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='diseasedetection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diseasedetection',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diseasedetection',
            name='disease',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasedetection',
            name='plant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diseasedetection',
            name='severity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
